name: payu_payment
description: Simple PayU integration using WebView. Flexible and easy to set up.
version: 0.0.3
repository: https://github.com/lukeurban/payu_payment

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.4
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  plugin:
    platforms:
      android:
        package: com.lukeurban.payu_flutter
        pluginClass: PayuFlutterPlugin
      ios:
        pluginClass: PayuFlutterPlugin