name: payu_flutter
description: Simple PayU integration using WebView
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^1.0.7
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  plugin:
    platforms:
      android:
        package: com.lukeurban.payu_flutter
        pluginClass: PayuFlutterPlugin
      ios:
        pluginClass: PayuFlutterPlugin